// client/src/pages/MesReservations.jsx
import { useState, useEffect } from "react";
import { motion } from "framer-motion";
import reservationService from "../services/reservation.service";
import Toast from "../components/Toast";
import TicketModal from "../components/TicketModal";
import "../styles/dashboard.css";

const statutLabel = {
  en_attente: "En attente",
  confirmee: "Confirmée",
  annulee: "Annulée",
  refusee: "Refusée",
  terminee: "Terminée",
};

const statutPaiementLabel = {
  impaye: "Impayé",
  partiel: "Partiel",
  paye: "Payé",
  rembourse: "Remboursé",
};

const MesReservations = () => {
  const [reservations, setReservations] = useState([]);
  const [chargement, setChargement] = useState(true);
  const [toast, setToast] = useState(null);
  const [ticketId, setTicketId] = useState(null);

  useEffect(() => {
    const charger = async () => {
      try {
        const data = await reservationService.mesReservations();
        setReservations(data.reservations);
      } catch {
        setToast({ message: "Erreur de chargement.", type: "error" });
      } finally {
        setChargement(false);
      }
    };
    charger();
  }, []);

  const handleAnnuler = async (id) => {
    try {
      await reservationService.annuler(id);
      setReservations((prev) =>
        prev.map((r) => (r._id === id ? { ...r, statut: "annulee" } : r))
      );
      setToast({ message: "Réservation annulée.", type: "success" });
    } catch {
      setToast({ message: "Erreur lors de l'annulation.", type: "error" });
    }
  };

  const formatDate = (d) => new Date(d).toLocaleDateString("fr-FR", {
    day: "numeric", month: "long", year: "numeric",
  });

  const peutAfficherTicket = (r) => r.statut === "confirmee" || r.statut === "terminee";

  return (
    <div className="dashboard-page">
      {toast && <Toast {...toast} onClose={() => setToast(null)} />}
      {ticketId && <TicketModal reservationId={ticketId} onClose={() => setTicketId(null)} />}

      <div className="dashboard-header">
        <h1>Mes réservations</h1>
        <p>Consultez et gérez vos réservations.</p>
      </div>

      {chargement ? (
        <div className="trajets-grid">
          {[1, 2, 3].map((n) => (
            <div key={n} className="skeleton-card">
              <div className="skeleton skeleton-title" />
              <div className="skeleton skeleton-text" />
            </div>
          ))}
        </div>
      ) : reservations.length === 0 ? (
        <div className="empty-state">
          <h3>Aucune réservation</h3>
          <p>Vous n'avez pas encore effectué de réservation.</p>
        </div>
      ) : (
        <div className="table-container">
          <table>
            <thead>
              <tr>
                <th>Trajet</th>
                <th>Date</th>
                <th>Places</th>
                <th>Total</th>
                <th>Statut</th>
                <th>Paiement</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody>
              {reservations.map((r) => (
                <motion.tr
                  key={r._id}
                  initial={{ opacity: 0 }}
                  animate={{ opacity: 1 }}
                  transition={{ duration: 0.3 }}
                >
                  <td>
                    <strong>{r.trajet?.titre || "Trajet"}</strong>
                    <br />
                    <span style={{ fontSize: "0.8rem", color: "#6b7280" }}>
                      {r.trajet?.villeDepart} → {r.trajet?.villeArrivee}
                    </span>
                  </td>
                  <td>{r.trajet ? formatDate(r.trajet.dateDepart) : "-"}</td>
                  <td>{r.nombrePlaces}</td>
                  <td><strong>{r.montantTotal.toLocaleString()} Ar</strong></td>
                  <td><span className={`badge ${r.statut}`}>{statutLabel[r.statut]}</span></td>
                  <td><span className={`badge ${r.statutPaiement}`}>{statutPaiementLabel[r.statutPaiement]}</span></td>
                  <td>
                    <div style={{ display: "flex", gap: "0.25rem", flexWrap: "wrap" }}>
                      {peutAfficherTicket(r) && (
                        <button className="btn-action blue" onClick={() => setTicketId(r._id)}>
                          🎫 Ticket
                        </button>
                      )}
                      {r.statut === "en_attente" && (
                        <button className="btn-action red" onClick={() => handleAnnuler(r._id)}>
                          Annuler
                        </button>
                      )}
                    </div>
                  </td>
                </motion.tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </div>
  );
};

export default MesReservations;

// client/src/pages/MesReservations.vue
<template>
  <div class="dashboard-page">
    <Toast :message="toast?.message" :type="toast?.type" @close="toast = null" />
    <TicketModal v-if="ticketId" :reservation-id="ticketId" @close="ticketId = null" />

    <div class="dashboard-header">
      <h1>Mes réservations</h1>
      <p>Consultez et gérez vos réservations.</p>
    </div>

    <div v-if="chargement" class="trajets-grid">
      <div v-for="n in 3" :key="n" class="skeleton-card">
        <div class="skeleton skeleton-title" />
        <div class="skeleton skeleton-text" />
      </div>
    </div>

    <div v-else-if="reservations.length === 0" class="empty-state">
      <h3>Aucune réservation</h3>
      <p>Vous n'avez pas encore effectué de réservation.</p>
    </div>

    <div v-else class="table-container">
      <table>
        <thead>
          <tr>
            <th>Trajet</th>
            <th>Date</th>
            <th>Places</th>
            <th>Total</th>
            <th>Statut</th>
            <th>Paiement</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="r in reservations" :key="r._id" class="fade-row">
            <td>
              <strong>{{ r.trajet?.titre || "Trajet" }}</strong>
              <br />
              <span style="font-size: 0.8rem; color: #6b7280">
                {{ r.trajet?.villeDepart }} → {{ r.trajet?.villeArrivee }}
              </span>
            </td>
            <td>{{ r.trajet ? formatDate(r.trajet.dateDepart) : "-" }}</td>
            <td>{{ r.nombrePlaces }}</td>
            <td><strong>{{ r.montantTotal.toLocaleString() }} Ar</strong></td>
            <td><span :class="['badge', r.statut]">{{ statutLabel[r.statut] }}</span></td>
            <td><span :class="['badge', r.statutPaiement]">{{ statutPaiementLabel[r.statutPaiement] }}</span></td>
            <td>
              <div style="display: flex; gap: 0.25rem; flex-wrap: wrap">
                <button v-if="peutAfficherTicket(r)" class="btn-action blue" @click="ticketId = r._id">
                  🎫 Ticket
                </button>
                <button v-if="r.statut === 'en_attente'" class="btn-action red" @click="handleAnnuler(r._id)">
                  Annuler
                </button>
              </div>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</template>

<script setup>
import { ref, onMounted } from "vue";
import reservationService from "../services/reservation.service";
import Toast from "../components/Toast.vue";
import TicketModal from "../components/TicketModal.vue";
import "../styles/dashboard.css";

const statutLabel = {
  en_attente: "En attente",
  confirmee: "Confirmée",
  annulee: "Annulée",
  refusee: "Refusée",
  terminee: "Terminée",
};

const statutPaiementLabel = {
  impaye: "Impayé",
  partiel: "Partiel",
  paye: "Payé",
  rembourse: "Remboursé",
};

const reservations = ref([]);
const chargement = ref(true);
const toast = ref(null);
const ticketId = ref(null);

onMounted(async () => {
  try {
    const data = await reservationService.mesReservations();
    reservations.value = data.reservations;
  } catch {
    toast.value = { message: "Erreur de chargement.", type: "error" };
  } finally {
    chargement.value = false;
  }
});

const handleAnnuler = async (id) => {
  try {
    await reservationService.annuler(id);
    reservations.value = reservations.value.map((r) =>
      r._id === id ? { ...r, statut: "annulee" } : r
    );
    toast.value = { message: "Réservation annulée.", type: "success" };
  } catch {
    toast.value = { message: "Erreur lors de l'annulation.", type: "error" };
  }
};

const formatDate = (d) => new Date(d).toLocaleDateString("fr-FR", {
  day: "numeric", month: "long", year: "numeric",
});

const peutAfficherTicket = (r) => r.statut === "confirmee" || r.statut === "terminee";
</script>

<style scoped>
.fade-row {
  animation: fadeIn 0.3s ease;
}
@keyframes fadeIn {
  from { opacity: 0; }
  to { opacity: 1; }
}
</style>
